// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUwaJTmxIJMz8Vx4-piKeFe3vg5VSP0fI',
    appId: '1:889937357311:web:6c28299f5fa7513a39dfca',
    messagingSenderId: '889937357311',
    projectId: 'upstart-a1937',
    authDomain: 'upstart-a1937.firebaseapp.com',
    storageBucket: 'upstart-a1937.firebasestorage.app',
    measurementId: 'G-S8CGCYJVZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw_haELRt6w1JRdn58INbtI-6lbCW9Krs',
    appId: '1:889937357311:android:3fe1970ed8eea70139dfca',
    messagingSenderId: '889937357311',
    projectId: 'upstart-a1937',
    storageBucket: 'upstart-a1937.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3QuVtUs3PoNsikpuVZUKmrVmpZ7OOXBo',
    appId: '1:889937357311:ios:8d13dd769116edad39dfca',
    messagingSenderId: '889937357311',
    projectId: 'upstart-a1937',
    storageBucket: 'upstart-a1937.firebasestorage.app',
    iosBundleId: 'com.example.startup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3QuVtUs3PoNsikpuVZUKmrVmpZ7OOXBo',
    appId: '1:889937357311:ios:8d13dd769116edad39dfca',
    messagingSenderId: '889937357311',
    projectId: 'upstart-a1937',
    storageBucket: 'upstart-a1937.firebasestorage.app',
    iosBundleId: 'com.example.startup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUwaJTmxIJMz8Vx4-piKeFe3vg5VSP0fI',
    appId: '1:889937357311:web:237b02fca3287a8439dfca',
    messagingSenderId: '889937357311',
    projectId: 'upstart-a1937',
    authDomain: 'upstart-a1937.firebaseapp.com',
    storageBucket: 'upstart-a1937.firebasestorage.app',
    measurementId: 'G-YNLG6H58FL',
  );
}
